name: sura_manager
description: A custom ValueNotifier and ValueListenableBuilder that support asynchronus value handling.
version: 0.1.3
homepage: https://github.com/asurraa/sura_manager

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.0
  sura_flutter: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
