name: sura_manager
description: ValueNotifier and ValueListenableBuilder but for asynchronous value.
version: 1.5.0
homepage: https://github.com/asurraa/sura_manager
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.0
  # sura_flutter: ^1.1.0
  sura_flutter:
    git:
      url: https://github.com/Sovann72/sura-flutter.git
      branch: master

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter
flutter:
